apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cimeem-docker-deployment
  labels:
    app: k8s-cimeem-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cimeem-docker
  template:
    metadata:
      labels:
        app: k8s-cimeem-docker
    spec:
      containers:
      - name: k8s-cimeem-docker
        image: anhthu1302/cimeem-docker:v1.0.0
        ports:
        - containerPort: 8085